import tkinter as tk
import tkinter.messagebox as msgbox
def shifr():
    b = text.get()
    try:
        if ozgar.get() == 1:
            b = b.replace("A", "1000001 ")
            b = b.replace("B", "1000010 ")   
            b = b.replace("D", "1000100 ")
            b = b.replace("E", "1000101 ")
            b = b.replace("F", "1000110 ")
            b = b.replace("G", "1000111 ")
            b = b.replace("H", "1001000 ")
            b = b.replace("I", "1001001 ")
            b = b.replace("J", "1001010 ")
            b = b.replace("K", "1001011 ")
            b = b.replace("L", "1001100 ")
            b = b.replace("M", "1001101 ")
            b = b.replace("N", "1001110 ")
            b = b.replace("O", "1001111 ")
            b = b.replace("P", "1010000 ")
            b = b.replace("Q", "1010001 ")
            b = b.replace("R", "1010010 ")
            b = b.replace("S", "1010011 ")
            b = b.replace("T", "1010100 ")
            b = b.replace("U", "1010101 ")
            b = b.replace("V", "1010110 ")
            b = b.replace("W", "1010111 ")
            b = b.replace("X", "1011000 ")
            b = b.replace("Y", "1011001 ")
            b = b.replace("Z", "1011010 ")
            b = b.replace("a", "1100001 ")
            b = b.replace("b", "1100010 ")
            b = b.replace("c", "1100011 ")
            b = b.replace("d", "1100100 ")
            b = b.replace("e", "1100101 ")
            b = b.replace("f", "1100110 ")
            b = b.replace("g", "1100111 ")
            b = b.replace("h", "1101000 ")
            b = b.replace("i", "1101001 ")
            b = b.replace("j", "1101010 ")
            b = b.replace("k", "1101011 ")
            b = b.replace("l", "1101100 ")
            b = b.replace("m", "1101101 ")
            b = b.replace("n", "1101110 ")
            b = b.replace("o", "1101111 ")
            b = b.replace("p", "1110000 ")
            b = b.replace("q", "1110001 ")
            b = b.replace("r", "1110010 ")
            b = b.replace("s", "1110011 ")
            b = b.replace("t", "1110100 ")  
            b = b.replace("u", "1110101 ")
            b = b.replace("v", "1110110 ")
            b = b.replace("w", "1110111 ")
            b = b.replace("x", "1111000 ")
            b = b.replace("y", "1111001 ")
            b = b.replace("z", "1111010 ")  

            
        elif ozgar.get() == 2:
            b = b.replace("1000001", "A")
            b = b.replace("1000010", "B")
            b = b.replace("1000011", "C")
            b = b.replace("1000100", "D")
            b = b.replace("1000101", "E")
            b = b.replace("1000110", "F")
            b = b.replace("1000111", "G")
            b = b.replace("1001000", "H")
            b = b.replace("1001001", "I")
            b = b.replace("1001010", "J")
            b = b.replace("1001011", "K")
            b = b.replace("1001100", "L")
            b = b.replace("1001101", "M")
            b = b.replace("1001110", "N")
            b = b.replace("1001111", "O")
            b = b.replace("1010000", "P")
            b = b.replace("1010001", "Q")
            b = b.replace("1010010", "R")
            b = b.replace("1010011", "S")
            b = b.replace("1010100", "T")
            b = b.replace("1010101", "U")
            b = b.replace("1010110", "V")
            b = b.replace("1010111", "W")
            b = b.replace("1011000", "X")
            b = b.replace("1011001", "Y")
            b = b.replace("1011010", "Z")
            b = b.replace("1100001", "a")   
            b = b.replace("1100010", "b")
            b = b.replace("1100011", "c")
            b = b.replace("1100100", "d")
            b = b.replace("1100101", "e")
            b = b.replace("1100110", "f")
            b = b.replace("1100111", "g")
            b = b.replace("1101000", "h")
            b = b.replace("1101001", "i")
            b = b.replace("1101010", "j")
            b = b.replace("1101011", "k")
            b = b.replace("1101100", "l")
            b = b.replace("1101101", "m")
            b = b.replace("1101110", "n")
            b = b.replace("1101111", "o")
            b = b.replace("1110000", "p")
            b = b.replace("1110001", "q")
            b = b.replace("1110010", "r") 
            b = b.replace("1110011", "s")
            b = b.replace("1110100", "t")
            b = b.replace("1110101", "u")
            b = b.replace("1110110", "v")
            b = b.replace("1110111", "w")
            b = b.replace("1111000", "x") 
            b = b.replace("1111001", "y")
            b = b.replace("1111010", "z")         
             
        elif ozgar.get() == 3:
            b = b.replace("A", "101 ")
            b = b.replace("B", "102 ")
            b = b.replace("C", "103 ")
            b = b.replace("D", "104 ")
            b = b.replace("E", "105 ")
            b = b.replace("F", "106 ")
            b = b.replace("G", "107 ")
            b = b.replace("H", "110 ")  
            b = b.replace("I", "111 ")
            b = b.replace("J", "112 ")
            b = b.replace("K", "113 ")
            b = b.replace("L", "114 ")
            b = b.replace("M", "115 ")
            b = b.replace("N", "116 ")
            b = b.replace("O", "117 ")
            b = b.replace("P", "120 ")  
            b = b.replace("Q", "121 ")
            b = b.replace("R", "122 ")
            b = b.replace("S", "123 ")
            b = b.replace("T", "124 ")
            b = b.replace("U", "125 ")
            b = b.replace("V", "126 ")
            b = b.replace("W", "127 ")
            b = b.replace("X", "130 ")
            b = b.replace("Y", "131 ")
            b = b.replace("Z", "132 ")
            b = b.replace("a", "141 ")
            b = b.replace("b", "142 ")
            b = b.replace("c", "143 ")
            b = b.replace("d", "144 ")
            b = b.replace("e", "145 ")
            b = b.replace("f", "146 ")
            b = b.replace("g", "147 ")
            b = b.replace("h", "150 ")
            b = b.replace("i", "151 ")
            b = b.replace("j", "152 ")
            b = b.replace("k", "153 ")
            b = b.replace("l", "154 ")
            b = b.replace("m", "155 ")
            b = b.replace("n", "156 ")
            b = b.replace("o", "157 ")
            b = b.replace("p", "160 ")
            b = b.replace("q", "161 ")
            b = b.replace("r", "162 ")
            b = b.replace("s", "163 ")
            b = b.replace("t", "164 ")
            b = b.replace("u", "165 ")
            b = b.replace("v", "166 ")
            b = b.replace("w", "167 ")
            b = b.replace("x", "170 ")
            b = b.replace("y", "171 ")
            b = b.replace("z", "172 ")
        elif ozgar.get() == 4:
            b = b.replace("101", "A")
            b = b.replace("102", "B")
            b = b.replace("103", "C")
            b = b.replace("104", "D")
            b = b.replace("105", "E")
            b = b.replace("106", "F")
            b = b.replace("107", "G")
            b = b.replace("110", "H")
            b = b.replace("111", "I")
            b = b.replace("112", "J")
            b = b.replace("113", "K")
            b = b.replace("114", "L")   
            b = b.replace("115", "M")
            b = b.replace("116", "N")
            b = b.replace("117", "O")
            b = b.replace("120", "P")
            b = b.replace("121", "Q")
            b = b.replace("122", "R")
            b = b.replace("123", "S")
            b = b.replace("124", "T")
            b = b.replace("125", "U")
            b = b.replace("126", "V")
            b = b.replace("127", "W")
            b = b.replace("130", "X")
            b = b.replace("131", "Y")
            b = b.replace("132", "Z")
            b = b.replace("141", "a")
            b = b.replace("142", "b")
            b = b.replace("143", "c")
            b = b.replace("144", "d")
            b = b.replace("145", "e")
            b = b.replace("146", "f")
            b = b.replace("147", "g")
            b = b.replace("150", "h")
            b = b.replace("151", "i")
            b = b.replace("152", "j")
            b = b.replace("153", "k")
            b = b.replace("154", "l")
            b = b.replace("155", "m")
            b = b.replace("156", "n")
            b = b.replace("157", "o")
            b = b.replace("160", "p")
            b = b.replace("161", "q")
            b = b.replace("162", "r")
            b = b.replace("163", "s")
            b = b.replace("164", "t")
            b = b.replace("165", "u")
            b = b.replace("166", "v")
            b = b.replace("167", "w")
            b = b.replace("170", "x")
            b = b.replace("171", "y")
            b = b.replace("172", "z")
        
        elif ozgar.get() == 5:
            b = b.replace("A", "41 ")
            b = b.replace("B", "42 ")
            b = b.replace("C", "43 ")
            b = b.replace("D", "44 ")
            b = b.replace("E", "45 ")
            b = b.replace("F", "46 ")
            b = b.replace("G", "47 ")
            b = b.replace("H", "48 ")
            b = b.replace("I", "49 ")
            b = b.replace("J", "4A ")
            b = b.replace("K", "4B ")
            b = b.replace("L", "4C ")
            b = b.replace("M", "4D ")
            b = b.replace("N", "4E ")
            b = b.replace("O", "4F ")
            b = b.replace("P", "50 ")
            b = b.replace("Q", "51 ")
            b = b.replace("R", "52 ")
            b = b.replace("S", "53 ")
            b = b.replace("T", "54 ")
            b = b.replace("U", "55 ")
            b = b.replace("V", "56 ")
            b = b.replace("W", "57 ")
            b = b.replace("X", "58 ")
            b = b.replace("Y", "59 ")
            b = b.replace("Z", "5A ")
            b = b.replace("a", "61 ")
            b = b.replace("b", "62 ")
            b = b.replace("c", "63 ")
            b = b.replace("d", "64 ")
            b = b.replace("e", "65 ")
            b = b.replace("f", "66 ")
            b = b.replace("g", "67 ")
            b = b.replace("h", "68 ")
            b = b.replace("i", "69 ")
            b = b.replace("j", "6A ")
            b = b.replace("k", "6B ")
            b = b.replace("l", "6C ")
            b = b.replace("m", "6D ")
            b = b.replace("n", "6E ")
            b = b.replace("o", "6F ")
            b = b.replace("p", "70 ")
            b = b.replace("q", "71 ")
            b = b.replace("r", "72 ")
            b = b.replace("s", "73 ")
            b = b.replace("t", "74 ")
            b = b.replace("u", "75 ")
            b = b.replace("v", "76 ")
            b = b.replace("w", "77 ")
            b = b.replace("x", "78 ")
            b = b.replace("y", "79 ")
            b = b.replace("z", "7A ")
        
        elif ozgar.get() == 6:
            b = b.replace("41", "A")
            b = b.replace("42", "B")
            b = b.replace("43", "C")
            b = b.replace("44", "D")
            b = b.replace("45", "E")
            b = b.replace("46", "F")
            b = b.replace("47", "G")
            b = b.replace("48", "H")
            b = b.replace("49", "I")
            b = b.replace("4A", "J")
            b = b.replace("4B", "K")
            b = b.replace("4C", "L")
            b = b.replace("4D", "M")
            b = b.replace("4E", "N")
            b = b.replace("4F", "O")
            b = b.replace("50", "P")
            b = b.replace("51", "Q")
            b = b.replace("52", "R")
            b = b.replace("53", "S")
            b = b.replace("54", "T")
            b = b.replace("55", "U")
            b = b.replace("56", "V")
            b = b.replace("57", "W")
            b = b.replace("58", "X")
            b = b.replace("59", "Y")
            b = b.replace("5A", "Z")
            b = b.replace("61", "a")
            b = b.replace("62", "b")
            b = b.replace("63", "c")
            b = b.replace("64", "d")
            b = b.replace("65", "e")
            b = b.replace("66", "f")
            b = b.replace("67", "g")
            b = b.replace("68", "h")
            b = b.replace("69", "i")
            b = b.replace("6A", "j")
            b = b.replace("6B", "k")
            b = b.replace("6C", "l")
            b = b.replace("6D", "m")
            b = b.replace("6E", "n")
            b = b.replace("6F", "o")
            b = b.replace("70", "p")
            b = b.replace("71", "q")
            b = b.replace("72", "r")
            b = b.replace("73", "s")
            b = b.replace("74", "t")
            b = b.replace("75", "u")
            b = b.replace("76", "v")
            b = b.replace("77", "w")
            b = b.replace("78", "x")
            b = b.replace("79", "y")
            b = b.replace("7A", "z")



                              
        
        else:
            raise ValueError("Xato")
        maydon.delete(1.0, tk.END)
        maydon.insert(tk.END, b)
    except ValueError as e:
        msgbox.showerror("Error", str(e))

def parol1():
    if parol.get() == "BEKFURR IS BEST FOREVER":
        msgbox.showinfo("Tasdiqlash", "Parol tasdiqlandi!")
        win2 = tk.Toplevel(oyna)
        win2.title("SHIFRATOR")
        tk.Label(win2, text="TEXTNI KIRITNG:").pack()
        
        global text, maydon, ozgar
        text = tk.Entry(win2, width=70)
        text.pack()
        
        tk.Button(win2, text="SHIFRALASH", command=shifr).pack()
        
        maydon = tk.Text(win2, height=10, width=50)
        maydon.pack()
        tk.Label(win2, text="Shifr turini tanlang:").pack()
        ozgar = tk.IntVar()
        ozgar.set(1)
        
        tk.Radiobutton(win2, text="text to binary", variable=ozgar, value=1).pack()
        tk.Radiobutton(win2, text="binary to text", variable=ozgar, value=2).pack()
        tk.Radiobutton(win2, text="text to Oct", variable=ozgar, value=3).pack()
        tk.Radiobutton(win2, text="oct to text", variable=ozgar, value=4).pack()
        tk.Radiobutton(win2, text="text to Hexagon", variable=ozgar, value=5).pack()
        tk.Radiobutton(win2, text="Hexagon to text", variable=ozgar, value=6).pack()
        tk.Button(win2, text="Dastur xaqida",fg="RED", font="BOLD", command=malumot).pack()
    else:
        msgbox.showerror("Tasdiqlash", '''Parol xato! 
                         Podskaska: BEKFURR IS BEST FOREVER''')
def malumot():
    msgbox.showinfo("Dastur xaqida", '''Bu dastur @BEKFURR tomonida yozildi: Bu dastur Textni raqamlarga shifrlaydi va dishifrlaydi
                    Podskaska: BEKFURR IS BEST FOREVER''')
oyna = tk.Tk()
oyna.title("NUMERICAL CONVERTER")


tk.Label(oyna, text="Parolni kiriting:").grid(row=0, column=0)

parol = tk.Entry(oyna, show="*", width=60)
parol.grid(row=0, column=1)

tk.Button(oyna, text="Tasdiqlash", command=parol1).grid(row=1, column=1)
tk.Button(oyna, text="Dastur xaqida",fg="RED", font="BOLD", command=malumot).grid(row=2, column=1)

oyna.mainloop()





#CODED FROM @BEKFURR NOCOPYRIGHtS 2024-2024